"""empty message

Revision ID: 6d022234b72d
Revises: 
Create Date: 2025-05-22 00:09:56.411251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d022234b72d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('group_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_name', sa.String(length=18), nullable=False),
    sa.PrimaryKeyConstraint('group_id')
    )
    op.create_table('programs',
    sa.Column('program_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('program_name', sa.String(length=24), nullable=False),
    sa.PrimaryKeyConstraint('program_id')
    )
    op.create_table('g2p',
    sa.Column('relation_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.group_id'], ),
    sa.ForeignKeyConstraint(['program_id'], ['programs.program_id'], ),
    sa.PrimaryKeyConstraint('relation_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_name', sa.String(length=100), nullable=False),
    sa.Column('user_phone', sa.String(length=15), nullable=False),
    sa.Column('user_password', sa.String(length=20), nullable=False),
    sa.Column('user_group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_group_id'], ['groups.group_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('g2p')
    op.drop_table('programs')
    op.drop_table('groups')
    # ### end Alembic commands ###
