"""empty message

Revision ID: 97b5bf0bcbd7
Revises: 6d022234b72d
Create Date: 2025-06-03 01:14:04.742766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97b5bf0bcbd7'
down_revision: Union[str, None] = '6d022234b72d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_roles',
    sa.Column('role_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role_name', sa.String(), nullable=False),
    sa.Column('read_and_download_lessons', sa.Boolean(), nullable=False),
    sa.Column('generating_report', sa.Boolean(), nullable=False),
    sa.Column('voting', sa.Boolean(), nullable=False),
    sa.Column('checking_marks', sa.Boolean(), nullable=False),
    sa.Column('give_marks', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('role_id')
    )
    op.create_unique_constraint(None, 'groups', ['group_name'])
    op.add_column('users', sa.Column('user_email', sa.String(length=40), nullable=False))
    op.create_unique_constraint(None, 'users', ['user_phone'])
    op.create_unique_constraint(None, 'users', ['user_email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'user_email')
    op.drop_constraint(None, 'groups', type_='unique')
    op.drop_table('access_roles')
    # ### end Alembic commands ###
